# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
